# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mainwidget.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(343, 333)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(320, 280))
        MainWindow.setMaximumSize(QtCore.QSize(360, 360))
        MainWindow.setStyleSheet("")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(360, 340))
        self.centralwidget.setMaximumSize(QtCore.QSize(500, 500))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 335, 313))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.horizontalLayoutWidget)
        self.gridLayout_4.setContentsMargins(10, 0, 0, 0)
        self.gridLayout_4.setVerticalSpacing(12)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.opn_folder_btn = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.opn_folder_btn.sizePolicy().hasHeightForWidth())
        self.opn_folder_btn.setSizePolicy(sizePolicy)
        self.opn_folder_btn.setObjectName("opn_folder_btn")
        self.gridLayout_4.addWidget(self.opn_folder_btn, 0, 2, 1, 1)
        self.d_min_input = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.d_min_input.sizePolicy().hasHeightForWidth())
        self.d_min_input.setSizePolicy(sizePolicy)
        self.d_min_input.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.d_min_input.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.d_min_input.setObjectName("d_min_input")
        self.gridLayout_4.addWidget(self.d_min_input, 11, 1, 1, 1)
        self.wavelength_inp = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wavelength_inp.sizePolicy().hasHeightForWidth())
        self.wavelength_inp.setSizePolicy(sizePolicy)
        self.wavelength_inp.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.wavelength_inp.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.wavelength_inp.setObjectName("wavelength_inp")
        self.gridLayout_4.addWidget(self.wavelength_inp, 8, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 8, 0, 1, 1)
        self.logtext = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.logtext.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logtext.sizePolicy().hasHeightForWidth())
        self.logtext.setSizePolicy(sizePolicy)
        self.logtext.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.logtext.setObjectName("logtext")
        self.gridLayout_4.addWidget(self.logtext, 14, 1, 1, 1)
        self.clean_diamonds_cb = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.clean_diamonds_cb.setEnabled(True)
        self.clean_diamonds_cb.setChecked(True)
        self.clean_diamonds_cb.setObjectName("clean_diamonds_cb")
        self.gridLayout_4.addWidget(self.clean_diamonds_cb, 4, 0, 1, 1)
        self.int_cutoff = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.int_cutoff.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.int_cutoff.setObjectName("int_cutoff")
        self.gridLayout_4.addWidget(self.int_cutoff, 12, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 11, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 6, 0, 1, 1)
        self.dspacings_line = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dspacings_line.sizePolicy().hasHeightForWidth())
        self.dspacings_line.setSizePolicy(sizePolicy)
        self.dspacings_line.setMaximumSize(QtCore.QSize(340, 16777215))
        self.dspacings_line.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.dspacings_line.setText("")
        self.dspacings_line.setObjectName("dspacings_line")
        self.gridLayout_4.addWidget(self.dspacings_line, 6, 1, 1, 1)
        self.fileinp_text = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.fileinp_text.setObjectName("fileinp_text")
        self.gridLayout_4.addWidget(self.fileinp_text, 0, 0, 1, 2)
        self.deltatheta_inp = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deltatheta_inp.sizePolicy().hasHeightForWidth())
        self.deltatheta_inp.setSizePolicy(sizePolicy)
        self.deltatheta_inp.setMinimumSize(QtCore.QSize(25, 0))
        self.deltatheta_inp.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.deltatheta_inp.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.deltatheta_inp.setObjectName("deltatheta_inp")
        self.gridLayout_4.addWidget(self.deltatheta_inp, 9, 1, 1, 1)
        self.do_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.do_btn.setObjectName("do_btn")
        self.gridLayout_4.addWidget(self.do_btn, 14, 0, 1, 1)
        self.loadcif_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.loadcif_btn.setObjectName("loadcif_btn")
        self.gridLayout_4.addWidget(self.loadcif_btn, 10, 1, 1, 1)
        self.dspacings_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dspacings_btn.sizePolicy().hasHeightForWidth())
        self.dspacings_btn.setSizePolicy(sizePolicy)
        self.dspacings_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.dspacings_btn.setText("")
        self.dspacings_btn.setObjectName("dspacings_btn")
        self.gridLayout_4.addWidget(self.dspacings_btn, 6, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 9, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 12, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setToolTip("")
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 5, 0, 1, 1)
        self.tolerance_inp = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.tolerance_inp.setObjectName("tolerance_inp")
        self.gridLayout_4.addWidget(self.tolerance_inp, 5, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PeakСleanerPro 0.0.3"))
        self.opn_folder_btn.setText(_translate("MainWindow", "Load"))
        self.d_min_input.setText(_translate("MainWindow", "0.9"))
        self.wavelength_inp.setText(_translate("MainWindow", "0.2900"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p>Wavelength</p></body></html>"))
        self.logtext.setText(_translate("MainWindow", "<html><head/><body><p>Please provide .tabbin file (<span style=\" color:#ff0000;\">wd t</span>)</p></body></html>"))
        self.clean_diamonds_cb.setText(_translate("MainWindow", "Clean Diamonds?"))
        self.int_cutoff.setText(_translate("MainWindow", "10"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p>Minimum d-spacing for cif</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>Clean <span style=\" font-style:italic;\">d</span>-spacings</p></body></html>"))
        self.dspacings_line.setPlaceholderText(_translate("MainWindow", "separated by space"))
        self.fileinp_text.setText(_translate("MainWindow", "D:\\Current data\\test_script\\enst\\s1\\ESPERANTO\\1.tabbin"))
        self.fileinp_text.setPlaceholderText(_translate("MainWindow", "provide .tabbin file"))
        self.deltatheta_inp.setText(_translate("MainWindow", "0.2"))
        self.deltatheta_inp.setPlaceholderText(_translate("MainWindow", "Δd"))
        self.do_btn.setText(_translate("MainWindow", "Clean Peaks"))
        self.loadcif_btn.setText(_translate("MainWindow", "Generate d-spacings from cif"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'Times New Roman,serif\'; font-size:9pt;\">Δ2θ </span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "Intensity cutoff for cif"))
        self.label.setText(_translate("MainWindow", "Tolerance (pixels)"))
        self.tolerance_inp.setText(_translate("MainWindow", "0"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
